# Generated by Django 4.2.4 on 2023-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('content', models.IntegerField(max_length=500)),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
