# Generated by Django 4.2.4 on 2023-09-03 11:56

from django.db import migrations, models
import task.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1f799c98-38fd-404c-8684-0060d869e1ce'), primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('team', models.CharField(max_length=200, validators=[task.models.validate_team_list])),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
