# Generated by Django 4.2.4 on 2023-09-03 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudTask',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bab93c03-03e2-457f-ae2c-e9ab5809fc7d'), primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=30)),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
