# Generated by Django 4.2.4 on 2023-09-03 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sub_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudtask',
            name='id',
            field=models.UUIDField(default=uuid.UUID('524caad2-0140-460d-9c16-0bacbf79e3cb'), primary_key=True, serialize=False),
        ),
    ]
